# Generated by Django 4.0.4 on 2022-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('week1', 'Week 1'), ('week2', 'Week 2'), ('week3', 'Week 3'), ('week4', 'Week 4'), ('week5', 'Week 5'), ('week6', 'Week 6'), ('week7', 'Week 7'), ('week8', 'Week 8')], max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('resource_person', models.CharField(max_length=100)),
            ],
        ),
    ]
